### ISSUE TITLE
Look over bosh deployment

### ISSUE THREAD

**Issue by tosin2013** [Altoros/s1p-bosh-lab#1]

**Comment by tosin2013** [comment]
## ISSUE REported by  cxhercules
I tried to run deployment in cloud shell but ran into some issues. I made some modifications on branch [updates-bosh-setup](https://github.com/tosin2013/altoros_bosh_training/tree/updates-bosh-setup). 

```
Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'stemcell-02228020-6704-4145-6a3b-c6ebd32285f3'... Finished (00:00:38)
  Waiting for the agent on VM 'vm-7d4bf91c-9432-42b3-57f9-bc3b486f4491' to be ready... Failed (00:10:09)
Failed deploying (00:10:48)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@104.196.67.116:6868/agent: dial tcp 104.196.67.116:6868: i/o timeout

Exit code 1
```

**Comment by s-matyukevich** [comment]
CloudShell is in a different VPC, I think you should use https://github.com/cloudfoundry/bosh-deployment/blob/master/external-ip-not-recommended.yml or write your own opfile to use SSH tunel in the CloudProvider block https://github.com/cloudfoundry/bosh-deployment/blob/04c85a5c79a9fa6b92775386a334104b9a165013/external-ip-with-registry-not-recommended.yml#L29
